# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TJ's Thoughts
email: devries.timothyj@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Various thoughts about Python, (neo)Vim, and other things I can think of
  that might be interesting to other people
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tjdevries.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  tjdevries

# Build settings
markdown: kramdown
theme: minima
